"""Generate custom_components/crowdsec/www/world-map.js.

Downloads the Natural Earth 110m country shapes (world-atlas TopoJSON) and
the ISO 3166 numeric -> alpha-2 mapping, projects the shapes to SVG paths
(equirectangular, Antarctica cropped) and writes them as a small ES module
consumed by crowdsec-card.js.

Usage: python tools/generate_world_map.py [cache_dir]
If cache_dir contains countries-110m.json / iso-codes.json they are reused.
"""
import json
import os
import sys
import urllib.request

TOPO_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json"
ISO_URL = ("https://raw.githubusercontent.com/lukes/"
           "ISO-3166-Countries-with-Regional-Codes/master/all/all.json")

W = 800.0
LAT_MAX, LAT_MIN = 84.0, -57.0
H = round(W * (LAT_MAX - LAT_MIN) / 360.0, 1)  # ~313.3

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "custom_components", "crowdsec", "www", "world-map.js")


def fetch(url, cache_dir, name):
    if cache_dir:
        path = os.path.join(cache_dir, name)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                return json.load(f)
    with urllib.request.urlopen(url) as resp:
        return json.loads(resp.read().decode("utf-8"))


def project(lon, lat):
    return (round((lon + 180.0) / 360.0 * W, 1),
            round((LAT_MAX - lat) / (LAT_MAX - LAT_MIN) * H, 1))


def main():
    cache_dir = sys.argv[1] if len(sys.argv) > 1 else None
    topo = fetch(TOPO_URL, cache_dir, "countries-110m.json")
    iso = fetch(ISO_URL, cache_dir, "iso-codes.json")
    num_to_a2 = {e["country-code"]: e["alpha-2"] for e in iso}
    # De-facto code used by geo IP services for Kosovo (no official ISO code).
    by_name = {"Kosovo": "XK"}

    scale = topo["transform"]["scale"]
    translate = topo["transform"]["translate"]
    arcs = []
    for arc in topo["arcs"]:
        pts, x, y = [], 0, 0
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * scale[0] + translate[0], y * scale[1] + translate[1]))
        arcs.append(pts)

    def ring_lonlat(idxs):
        pts = []
        for idx in idxs:
            a = arcs[~idx][::-1] if idx < 0 else arcs[idx]
            if pts:
                a = a[1:]
            pts.extend(a)
        # Unwrap longitudes so rings crossing the antimeridian stay
        # contiguous instead of drawing a band across the whole map.
        unwrapped, prev = [], None
        for lon, lat in pts:
            if prev is not None:
                while lon - prev > 180:
                    lon -= 360
                while lon - prev < -180:
                    lon += 360
            unwrapped.append((lon, lat))
            prev = lon
        return unwrapped

    def ring_area(pts):
        s = 0.0
        for i in range(len(pts) - 1):
            s += pts[i][0] * pts[i + 1][1] - pts[i + 1][0] * pts[i][1]
        return abs(s) / 2.0

    def ring_to_path(pts):
        dedup = [pts[0]]
        for p in pts[1:]:
            if p != dedup[-1]:
                dedup.append(p)
        if len(dedup) < 4:
            return None
        return ("M%g %g" % dedup[0]
                + "".join("L%g %g" % p for p in dedup[1:-1]) + "Z")

    entries = []
    for geom in topo["objects"]["countries"]["geometries"]:
        cid = geom.get("id")
        name = (geom.get("properties") or {}).get("name", "?")
        if cid == "010":  # Antarctica, cropped out
            continue
        polys = [geom["arcs"]] if geom["type"] == "Polygon" else geom["arcs"]
        parts = []
        for poly in polys:
            for ring in poly:
                lonlat = ring_lonlat(ring)
                lons = [p[0] for p in lonlat]
                # Unwrapped rings may extend past +/-180: also emit a copy
                # shifted by 360 so the overflow shows on the other edge
                # (the SVG viewBox clips whatever falls outside).
                shifts = [0.0]
                if max(lons) > 180:
                    shifts.append(-360.0)
                if min(lons) < -180:
                    shifts.append(360.0)
                for shift in shifts:
                    pts = [project(lon + shift, lat) for lon, lat in lonlat]
                    if ring_area(pts) < 1.2:  # drop specks
                        continue
                    p = ring_to_path(pts)
                    if p:
                        parts.append(p)
        if parts:
            code = num_to_a2.get(cid) or by_name.get(name, "")
            entries.append({"c": code, "n": name, "d": "".join(parts)})

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/generate_world_map.py - do not edit by hand.\n")
        f.write("// Shapes: Natural Earth 110m via world-atlas; equirectangular projection.\n")
        f.write('export const WORLD_VIEWBOX = "0 0 %g %g";\n' % (W, H))
        f.write("export const WORLD = [\n")
        for e in entries:
            f.write(json.dumps(e, ensure_ascii=False) + ",\n")
        f.write("];\n")
    unmapped = [e["n"] for e in entries if not e["c"]]
    print("wrote %s (%d countries, %d without ISO alpha-2: %s)"
          % (OUT, len(entries), len(unmapped), ", ".join(unmapped) or "none"))


if __name__ == "__main__":
    main()
